feat(ci): enhance semantic versioning and deploy workflow with new tag extraction

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -45,7 +45,7 @@ jobs:
     if: ${{ !contains(github.event.head_commit.message, '[skip ci]') && (startsWith(github.event.head_commit.message, 'fix') || startsWith(github.event.head_commit.message, 'feat') || startsWith(github.event.head_commit.message, 'breaking') || startsWith(github.event.head_commit.message, 'Merge')) }}
     outputs:
       new_version: ${{ steps.semantic-release.outputs.new_version }}
-
+      new_tag: ${{ steps.semantic-release.outputs.new_tag }}
     permissions:
       actions: read
       contents: write
@@ -72,5 +72,77 @@ jobs:
           npx semantic-release | tee release.log
           VERSION=$(cat release.log | grep -oP '(?<=next release version is )[\d\.]+(-beta\.\d+)?')
           echo "new_version=$VERSION" >> $GITHUB_OUTPUT
+          echo "new_tag=$TAG" >> $GITHUB_OUTPUT
           echo "New version: $VERSION"
+          echo "New tag: $TAG"
 
+  deploy:
+    name: Deploy to GitHub Container Registry
+    runs-on: ubuntu-latest
+    needs: [semantic-version, build]
+    permissions:
+      actions: read
+      contents: write
+      packages: write
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # Fetch all history for accurate versioning
+          ref: ${{ needs.semantic-version.outputs.new_tag }}
+      - name: Extract Version from Tag
+        id: extract-version
+        run: |
+          RAW_VERSION=$(git describe --tags --exact-match || echo "")
+          if [ -z "$RAW_VERSION" ]; then
+            echo "No tag found, aborting workflow."
+            exit 1
+          fi
+          VERSION="${RAW_VERSION#v}"
+          echo "VERSION=$VERSION" >> $GITHUB_ENV
+
+      - name: Determine Docker Tags
+        id: determine-tags
+        run: |
+          if [[ "${{ env.VERSION }}" == *"beta"* ]]; then
+            echo "tags=type=raw,value=pre" >> $GITHUB_ENV
+          else
+            echo "tags=type=raw,value=latest" >> $GITHUB_ENV
+          fi
+          echo "Version: ${{ env.VERSION }}"
+
+      - name: Docker meta
+        id: meta
+        uses: docker/metadata-action@v5
+        with:
+          images: |
+            ghcr.io/${{ github.repository }}
+          tags: |
+            type=semver,pattern={{version}},value=${{ env.VERSION }}
+            type=semver,pattern={{major}}.{{minor}},value=${{ env.VERSION }}
+            type=semver,pattern={{major}},value=${{ env.VERSION }}
+            ${{ env.tags }}
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Build and push
+        uses: docker/build-push-action@v6
+        with:
+          platforms: linux/amd64
+          context: "{{defaultContext}}:src"
+          file: "./AgricultureManager.CoreApp/Dockerfile"
+          push: true
+          tags: ${{ steps.meta.outputs.tags }}
+          labels: ${{ steps.meta.outputs.labels }}
